### PR TITLE
Improve PHP 8.4+ support by avoiding implicitly nullable types

### PR DESCRIPTION
**Pull request by clue**
This changeset improves PHP 8.4+ support by avoiding implicitly nullable types as discussed in https://github.com/reactphp/promise/pull/260. The same idea applies, but v1 requires manual type checks to support legacy PHP versions as the nullable type syntax requires PHP 7.1+ otherwise.

Builds on top of #22, #21, https://github.com/reactphp/promise/pull/260 and https://github.com/reactphp/datagram/pull/59

### CODE REVIEW

**Comment by sharkydog** [comment]
Contructor is missing the nullable type:
```php
public function __construct(LoopInterface $loop = null)
```
should be:
```php
public function __construct(?LoopInterface $loop = null)
```

**Comment by clue** [comment]
@sharkydog This PR is the fix for exactly that. The signature you're quoting is pre-merge. `?LoopInterface` would need PHP 7.1+, `1.x` still supports 5.3+, hence the manual `instanceof` check.

**Comment by sharkydog** [comment]
@clue I see now, I was looking at v1.2.0 tag. 
So this change is not in packagist.

**Comment by sharkydog** [comment]
Any reason not to tag it as v1.2.1 for example?

**Comment by clue** [comment]
@sharkydog Release is on the list, but may take a little while. I'm balancing this with a number of other open-source priorities and everything else going on, and there are follow-up PHP version updates that will likely need coordinating before the next push. Will get to it when time allows.

If this project matters to you, please consider [sponsoring](https://github.com/sponsors/clue). Every bit of support helps keep these projects alive, and knowing users actually care makes a real difference ❤️

**Pull request merged**
